apiVersion: api.sandeeppattnaik.online/v1alpha1
kind: Scaler
metadata:
  labels:
    app.kubernetes.io/name: scaleroperator
    app.kubernetes.io/managed-by: kustomize
  name: scaler-sample
spec:
  # TODO(user): Add fields here
  start: 0
  end: 10
  replicas: 5
  offPeakReplicas: 2
  deployments:
    - name: nginx
      namespace: default
